.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Steven Pusser (Stevo) <maintainer@mepiscommunity.org>,
.\"
.TH clocky-theme-manager SECTION "May 25, 2016"
.SH NAME
 clocky-theme-manager \- A theme manager for MX-Clocky.
.PP
\fB clocky-theme-manager\fP is a theme manager for MX-Clocky.
.SH OPTIONS
clocky-theme-manager has no command-line options.
