.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Steven Pusser (Stevo) <maintainer@mepiscommunity.org>,
.\"
.TH MX-CLOCKY SECTION "May 25, 2016"
.SH NAME
MX-Clocky \- An attractive, skinnable desktop analog clock.
.PP
\fBMX-Clocky\fP is an attractive, skinnable desktop analog clock.
.SH OPTIONS
MX-Clocky has no command-line options.
